# Generated by Django 3.0.8 on 2020-07-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20200707_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
